[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build --workspace=client"

[deploy]
startCommand = "npm start --workspace=server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/api/health"
timeout = 300
interval = 10
